#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Kinn Coelho Juliao <kinncj@gmail.com>
#
# Generate AUR PKGBUILDs for the prebuilt Heimdall binaries (the `-bin` packages,
# e.g. `paru -S heimdall-dashboard-bin`). Each package downloads the matching
# Linux release asset from GitHub and installs it to /usr/bin — no compilation.
#
# Usage:
#   VERSION=v1.4.0 SUMS=dist/SHA256SUMS OUT=aur-out bash packaging/aur/gen-pkgbuild.sh
#
# Environment:
#   VERSION     release tag, e.g. v1.4.0 (required). pkgver is the tag without the leading `v`.
#   SUMS        path to the release SHA256SUMS file (required). Lines: "<sha256>  heimdall-<c>_linux_<arch>".
#   OUT         output dir; one <pkgname>/PKGBUILD per component is written here (default: aur-out).
#   COMPONENTS  space-separated subset to generate (default: hub dashboard daemon helper).
#   REPO        owner/repo on GitHub (default: kinncj/Heimdall).
set -euo pipefail

VERSION="${VERSION:?set VERSION to the release tag, e.g. v1.4.0}"
SUMS="${SUMS:?set SUMS to the release SHA256SUMS file}"
OUT="${OUT:-aur-out}"
COMPONENTS="${COMPONENTS:-hub dashboard daemon helper cli}"
REPO="${REPO:-kinncj/Heimdall}"

[ -f "$SUMS" ] || { echo "gen-pkgbuild: SHA256SUMS not found at $SUMS" >&2; exit 1; }

pkgver="${VERSION#v}"
url="https://github.com/${REPO}"

# pkgdesc per component. Keep these one line; they become the AUR package summary.
desc_for() {
  case "$1" in
    hub)       echo "Heimdall hub — central gRPC server that ingests host metrics and fans them out to dashboards (prebuilt binary)" ;;
    dashboard) echo "Heimdall dashboard — real-time terminal UI rendering the whole fleet (prebuilt binary)" ;;
    daemon)    echo "Heimdall daemon — unprivileged per-host metric collector that streams to a hub (prebuilt binary)" ;;
    helper)    echo "Heimdall helper — optional root sidecar exposing privileged power/GPU/thermal metrics to the daemon (prebuilt binary)" ;;
    cli)       echo "Heimdall CLI — machine- and AI-friendly JSON client that queries a hub's fleet for scripts, CI/CD, and agents (prebuilt binary)" ;;
    *)         echo "Heimdall $1 (prebuilt binary)" ;;
  esac
}

# sha <component> <go-arch>  ->  prints the sha256 of heimdall-<c>_linux_<arch>.
sha() {
  local want="heimdall-${1}_linux_${2}"
  local hash
  hash="$(grep -E "  ${want}\$" "$SUMS" | awk '{print $1}' | head -1)"
  [ -n "$hash" ] || { echo "gen-pkgbuild: no checksum for ${want} in ${SUMS}" >&2; exit 1; }
  echo "$hash"
}

mkdir -p "$OUT"

for c in $COMPONENTS; do
  case "$c" in hub|dashboard|daemon|helper|cli) ;; *) echo "gen-pkgbuild: unknown component: $c" >&2; exit 1 ;; esac

  pkgname="heimdall-${c}-bin"
  pkgdir_out="${OUT}/${pkgname}"
  mkdir -p "$pkgdir_out"

  sha_amd64="$(sha "$c" amd64)"
  sha_arm64="$(sha "$c" arm64)"

  # daemon gains privileged metrics when the helper is present; surface it as optdepends.
  optdepends=""
  if [ "$c" = "daemon" ]; then
    optdepends=$'optdepends=(\'heimdall-helper-bin: privileged power, GPU, and full thermal metrics\')\n'
  fi

  cat > "${pkgdir_out}/PKGBUILD" <<EOF
# Maintainer: Kinn Coelho Juliao <kinncj@gmail.com>
# Generated by packaging/aur/gen-pkgbuild.sh — do not edit by hand.
pkgname=${pkgname}
pkgver=${pkgver}
pkgrel=1
pkgdesc="$(desc_for "$c")"
arch=('x86_64' 'aarch64')
url="${url}"
license=('AGPL-3.0-or-later')
provides=('heimdall-${c}')
conflicts=('heimdall-${c}')
${optdepends}source_x86_64=("heimdall-${c}_\${pkgver}_x86_64::${url}/releases/download/v\${pkgver}/heimdall-${c}_linux_amd64")
source_aarch64=("heimdall-${c}_\${pkgver}_aarch64::${url}/releases/download/v\${pkgver}/heimdall-${c}_linux_arm64")
sha256sums_x86_64=('${sha_amd64}')
sha256sums_aarch64=('${sha_arm64}')

package() {
    install -Dm755 "\${srcdir}/heimdall-${c}_\${pkgver}_\${CARCH}" "\${pkgdir}/usr/bin/heimdall-${c}"
}
EOF

  echo "wrote ${pkgdir_out}/PKGBUILD (heimdall-${c} ${pkgver})"
done
