// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Kinn Coelho Juliao <kinncj@gmail.com>
//
// Minimal Prometheus remote-write 1.0 schema — just the messages Heimdall's
// durable sink (Mímir, ADR 0016) needs to POST time series. This is the public
// remote-write wire contract; we vendor only the subset we use rather than
// depending on the full Prometheus module.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: common/proto/prometheus/v1/remote.proto

package prometheusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteRequest is the body of a Prometheus remote-write request (snappy-framed).
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeseries    []*TimeSeries          `protobuf:"bytes,1,rep,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_prometheus_v1_remote_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetTimeseries() []*TimeSeries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type TimeSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"` // includes __name__
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeries) Reset() {
	*x = TimeSeries{}
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeries) ProtoMessage() {}

func (x *TimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeries.ProtoReflect.Descriptor instead.
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return file_common_proto_prometheus_v1_remote_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSeries) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TimeSeries) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_common_proto_prometheus_v1_remote_proto_rawDescGZIP(), []int{2}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_prometheus_v1_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_common_proto_prometheus_v1_remote_proto_rawDescGZIP(), []int{3}
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_common_proto_prometheus_v1_remote_proto protoreflect.FileDescriptor

const file_common_proto_prometheus_v1_remote_proto_rawDesc = "" +
	"\n" +
	"'common/proto/prometheus/v1/remote.proto\x12\rprometheus.v1\"I\n" +
	"\fWriteRequest\x129\n" +
	"\n" +
	"timeseries\x18\x01 \x03(\v2\x19.prometheus.v1.TimeSeriesR\n" +
	"timeseries\"k\n" +
	"\n" +
	"TimeSeries\x12,\n" +
	"\x06labels\x18\x01 \x03(\v2\x14.prometheus.v1.LabelR\x06labels\x12/\n" +
	"\asamples\x18\x02 \x03(\v2\x15.prometheus.v1.SampleR\asamples\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"<\n" +
	"\x06Sample\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB2Z0heimdall/common/proto/prometheus/v1;prometheusv1b\x06proto3"

var (
	file_common_proto_prometheus_v1_remote_proto_rawDescOnce sync.Once
	file_common_proto_prometheus_v1_remote_proto_rawDescData []byte
)

func file_common_proto_prometheus_v1_remote_proto_rawDescGZIP() []byte {
	file_common_proto_prometheus_v1_remote_proto_rawDescOnce.Do(func() {
		file_common_proto_prometheus_v1_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_prometheus_v1_remote_proto_rawDesc), len(file_common_proto_prometheus_v1_remote_proto_rawDesc)))
	})
	return file_common_proto_prometheus_v1_remote_proto_rawDescData
}

var file_common_proto_prometheus_v1_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_prometheus_v1_remote_proto_goTypes = []any{
	(*WriteRequest)(nil), // 0: prometheus.v1.WriteRequest
	(*TimeSeries)(nil),   // 1: prometheus.v1.TimeSeries
	(*Label)(nil),        // 2: prometheus.v1.Label
	(*Sample)(nil),       // 3: prometheus.v1.Sample
}
var file_common_proto_prometheus_v1_remote_proto_depIdxs = []int32{
	1, // 0: prometheus.v1.WriteRequest.timeseries:type_name -> prometheus.v1.TimeSeries
	2, // 1: prometheus.v1.TimeSeries.labels:type_name -> prometheus.v1.Label
	3, // 2: prometheus.v1.TimeSeries.samples:type_name -> prometheus.v1.Sample
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_prometheus_v1_remote_proto_init() }
func file_common_proto_prometheus_v1_remote_proto_init() {
	if File_common_proto_prometheus_v1_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_prometheus_v1_remote_proto_rawDesc), len(file_common_proto_prometheus_v1_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_prometheus_v1_remote_proto_goTypes,
		DependencyIndexes: file_common_proto_prometheus_v1_remote_proto_depIdxs,
		MessageInfos:      file_common_proto_prometheus_v1_remote_proto_msgTypes,
	}.Build()
	File_common_proto_prometheus_v1_remote_proto = out.File
	file_common_proto_prometheus_v1_remote_proto_goTypes = nil
	file_common_proto_prometheus_v1_remote_proto_depIdxs = nil
}
