// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Kinn Coelho Juliao <kinncj@gmail.com>
//
// Heimdall monitoring contract — version 1.
//
// Single source of truth for the wire protocol shared by ALL binaries
// (heimdall-daemon, heimdall-helper, heimdall-hub, heimdall-dashboard).
// Every binary imports the generated types from this file; none defines a
// private copy. Versioning policy: see README.md in this directory.
//
// Design constraints reflected here:
//   - Low bandwidth: compact scalar timestamps (int64 unix-millis, no
//     well-known-type sub-message per sample), packed per-core arrays,
//     delta/keyframe snapshots, monotonic per-host sequence for resume.
//   - Failure isolation: every MetricSample carries its own MetricStatus, so
//     one failing metric is reported without dropping the host or siblings.
//   - Clean boundary: this file is a transport CONTRACT only. It contains no
//     business logic and no Go code. Domain types map to these messages at the
//     transport layer, never the reverse.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: monitoring/v1/monitoring.proto

package monitoringv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricStatus — adapter self-reported health for a single metric reading.
//
// METRIC_STATUS_UNSPECIFIED (0) is a safety guard: proto3 decodes an absent or
// truncated enum as 0, and a monitoring system must never read "missing" as
// "healthy". Consumers treat UNSPECIFIED as a non-OK, do-not-trust value.
type MetricStatus int32

const (
	MetricStatus_METRIC_STATUS_UNSPECIFIED             MetricStatus = 0
	MetricStatus_METRIC_STATUS_OK                      MetricStatus = 1 // value present and trustworthy
	MetricStatus_METRIC_STATUS_UNAVAILABLE             MetricStatus = 2 // adapter not applicable on this host
	MetricStatus_METRIC_STATUS_INSUFFICIENT_PERMISSION MetricStatus = 3 // needs privileged helper / denied
	MetricStatus_METRIC_STATUS_ERROR                   MetricStatus = 4 // adapter errored, timed out, panicked
)

// Enum value maps for MetricStatus.
var (
	MetricStatus_name = map[int32]string{
		0: "METRIC_STATUS_UNSPECIFIED",
		1: "METRIC_STATUS_OK",
		2: "METRIC_STATUS_UNAVAILABLE",
		3: "METRIC_STATUS_INSUFFICIENT_PERMISSION",
		4: "METRIC_STATUS_ERROR",
	}
	MetricStatus_value = map[string]int32{
		"METRIC_STATUS_UNSPECIFIED":             0,
		"METRIC_STATUS_OK":                      1,
		"METRIC_STATUS_UNAVAILABLE":             2,
		"METRIC_STATUS_INSUFFICIENT_PERMISSION": 3,
		"METRIC_STATUS_ERROR":                   4,
	}
)

func (x MetricStatus) Enum() *MetricStatus {
	p := new(MetricStatus)
	*p = x
	return p
}

func (x MetricStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_monitoring_v1_monitoring_proto_enumTypes[0].Descriptor()
}

func (MetricStatus) Type() protoreflect.EnumType {
	return &file_monitoring_v1_monitoring_proto_enumTypes[0]
}

func (x MetricStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricStatus.Descriptor instead.
func (MetricStatus) EnumDescriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{0}
}

// Host — stable identity of a monitored machine.
// host_id is content-derived and stable across restarts and reconnects so a
// returning daemon re-registers as the SAME host (no duplicate registration).
type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                // stable, opaque (e.g. hash of machine-id + pubkey)
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                          // OS hostname (may change; not used for identity)
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // operator-friendly label
	Context       *HostContext           `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`                            // slow-changing descriptive attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Host) GetContext() *HostContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// HostContext — locale / uptime / OS / host descriptors.
// Slow-changing; sent on enroll and refreshed on change, not every sample.
type HostContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"` // "linux" | "darwin" | "windows"
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"` // "amd64" | "arm64"
	Kernel        string                 `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Locale        string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`                                                                           // e.g. "en_US.UTF-8"
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`                                                                       // IANA tz, e.g. "America/New_York"
	BootTimeUnixS int64                  `protobuf:"varint,7,opt,name=boot_time_unix_s,json=bootTimeUnixS,proto3" json:"boot_time_unix_s,omitempty"`                                   // uptime is derived as now - boot_time
	AgentVersion  string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                                           // daemon build version
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // device class: {"class":"dgx-spark"} etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostContext) Reset() {
	*x = HostContext{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostContext) ProtoMessage() {}

func (x *HostContext) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostContext.ProtoReflect.Descriptor instead.
func (*HostContext) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *HostContext) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostContext) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HostContext) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostContext) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HostContext) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *HostContext) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *HostContext) GetBootTimeUnixS() int64 {
	if x != nil {
		return x.BootTimeUnixS
	}
	return 0
}

func (x *HostContext) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HostContext) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// PerCore — packed per-core readings (e.g. per-core CPU utilisation).
type PerCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerCore) Reset() {
	*x = PerCore{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerCore) ProtoMessage() {}

func (x *PerCore) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerCore.ProtoReflect.Descriptor instead.
func (*PerCore) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *PerCore) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Counter — a monotonic counter plus its derived per-second rate.
// Used for disk IO and network throughput where deltas are cheaper to ship
// than recomputed gauges.
type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // monotonic total since boot
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`  // derived units/second over the sample interval
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *Counter) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Counter) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// MetricSample — one metric reading from one adapter.
// The value lives in exactly one arm of the oneof. status is ALWAYS set so a
// non-OK metric (UNAVAILABLE / INSUFFICIENT_PERMISSION / ERROR) can be reported
// with no value arm at all — this is the failure-isolation guarantee on the wire.
type MetricSample struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Metric string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`                                  // canonical key, e.g. "cpu.core.util", "mem.used"
	Status MetricStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=monitoring.v1.MetricStatus" json:"status,omitempty"` // adapter self-report; never left at UNSPECIFIED by a healthy adapter
	Unit   string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                                      // "percent" | "bytes" | "celsius" | "bytes_per_sec" | "ms"
	Detail string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                                  // human-readable note, esp. for non-OK status
	// Types that are valid to be assigned to Value:
	//
	//	*MetricSample_Gauge
	//	*MetricSample_PerCore
	//	*MetricSample_Counter
	Value         isMetricSample_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *MetricSample) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricSample) GetStatus() MetricStatus {
	if x != nil {
		return x.Status
	}
	return MetricStatus_METRIC_STATUS_UNSPECIFIED
}

func (x *MetricSample) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricSample) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *MetricSample) GetValue() isMetricSample_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricSample) GetGauge() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricSample_Gauge); ok {
			return x.Gauge
		}
	}
	return 0
}

func (x *MetricSample) GetPerCore() *PerCore {
	if x != nil {
		if x, ok := x.Value.(*MetricSample_PerCore); ok {
			return x.PerCore
		}
	}
	return nil
}

func (x *MetricSample) GetCounter() *Counter {
	if x != nil {
		if x, ok := x.Value.(*MetricSample_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

type isMetricSample_Value interface {
	isMetricSample_Value()
}

type MetricSample_Gauge struct {
	Gauge float64 `protobuf:"fixed64,5,opt,name=gauge,proto3,oneof"` // single instantaneous value
}

type MetricSample_PerCore struct {
	PerCore *PerCore `protobuf:"bytes,6,opt,name=per_core,json=perCore,proto3,oneof"` // repeated per-core values
}

type MetricSample_Counter struct {
	Counter *Counter `protobuf:"bytes,7,opt,name=counter,proto3,oneof"` // monotonic counter + rate
}

func (*MetricSample_Gauge) isMetricSample_Value() {}

func (*MetricSample_PerCore) isMetricSample_Value() {}

func (*MetricSample_Counter) isMetricSample_Value() {}

// ProcessRow — one row of a pushed process table (Heimdallr's sight, ADR 0017):
// pid/ppid, the process's CPU% and memory%, and the command. The daemon collects
// it with an OS-appropriate command and pushes it periodically; it is never
// requested (the daemon does not serve).
type ProcessRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	CpuPct        float32                `protobuf:"fixed32,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemPct        float32                `protobuf:"fixed32,4,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRow) Reset() {
	*x = ProcessRow{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRow) ProtoMessage() {}

func (x *ProcessRow) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRow.ProtoReflect.Descriptor instead.
func (*ProcessRow) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessRow) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessRow) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessRow) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *ProcessRow) GetMemPct() float32 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *ProcessRow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// Snapshot — the metric set for one host at one instant (the streamed unit).
// Delta encoding: when delta=true, samples[] carries only metrics whose value
// or status changed since the last keyframe. keyframe=true marks a full set and
// is the resync point after reconnect. seq is monotonic per host for resume and
// duplicate suppression.
type Snapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	HostId       string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TsUnixMillis int64                  `protobuf:"varint,2,opt,name=ts_unix_millis,json=tsUnixMillis,proto3" json:"ts_unix_millis,omitempty"`
	Seq          uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`           // monotonic per-host sequence
	Delta        bool                   `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`       // true = changed samples only
	Keyframe     bool                   `protobuf:"varint,5,opt,name=keyframe,proto3" json:"keyframe,omitempty"` // true = full set (resync point)
	Samples      []*MetricSample        `protobuf:"bytes,6,rep,name=samples,proto3" json:"samples,omitempty"`
	Labels       map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // effective host tags (host wins over hub); inherited across Bifröst relay
	Alerts       []string               `protobuf:"bytes,8,rep,name=alerts,proto3" json:"alerts,omitempty"`                                                                           // names of rules currently firing for this host (Gjallarhorn)
	// Heimdallr's sight (ADR 0017) — additive, push-only host observability. Empty
	// unless the daemon is configured to push it; old peers ignore these fields.
	Processes             []*ProcessRow    `protobuf:"bytes,9,rep,name=processes,proto3" json:"processes,omitempty"`                                                            // latest process table
	ProcessesAtUnixMillis int64            `protobuf:"varint,10,opt,name=processes_at_unix_millis,json=processesAtUnixMillis,proto3" json:"processes_at_unix_millis,omitempty"` // when the process table was collected
	LogLines              []*LogLine       `protobuf:"bytes,11,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`                                             // log lines tailed since the last push (push tail)
	CommandResult         *ControlResponse `protobuf:"bytes,12,opt,name=command_result,json=commandResult,proto3" json:"command_result,omitempty"`                              // result of an on-demand command (v2), matched by request_id
	Disconnected          bool             `protobuf:"varint,13,opt,name=disconnected,proto3" json:"disconnected,omitempty"`                                                    // v2: the daemon's stream ended — host is offline NOW, not on a timeout. Old subscribers ignore this and fall back to the freshness window.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Snapshot) GetTsUnixMillis() int64 {
	if x != nil {
		return x.TsUnixMillis
	}
	return 0
}

func (x *Snapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Snapshot) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

func (x *Snapshot) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *Snapshot) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *Snapshot) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Snapshot) GetAlerts() []string {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *Snapshot) GetProcesses() []*ProcessRow {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Snapshot) GetProcessesAtUnixMillis() int64 {
	if x != nil {
		return x.ProcessesAtUnixMillis
	}
	return 0
}

func (x *Snapshot) GetLogLines() []*LogLine {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *Snapshot) GetCommandResult() *ControlResponse {
	if x != nil {
		return x.CommandResult
	}
	return nil
}

func (x *Snapshot) GetDisconnected() bool {
	if x != nil {
		return x.Disconnected
	}
	return false
}

// EnrollRequest — a daemon presents its enrollment token and self-declared
// identity. Optionally includes a CSR so the hub can issue a client cert for
// subsequent mTLS on the metric stream.
type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // bootstrap bearer secret (one-time / scoped)
	Host            *Host                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                                              // self-declared identity (host_id + context)
	CsrPem          string                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                            // optional PEM CSR for issued client certificate
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

// EnrollResponse — the hub confirms identity and returns stream policy.
type EnrollResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostId           string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // canonical id confirmed/assigned by the hub
	Accepted         bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                // populated when accepted=false (token rejected, etc.)
	SampleIntervalMs int32                  `protobuf:"varint,4,opt,name=sample_interval_ms,json=sampleIntervalMs,proto3" json:"sample_interval_ms,omitempty"` // hub-directed sampling cadence
	StaleAfterS      int32                  `protobuf:"varint,5,opt,name=stale_after_s,json=staleAfterS,proto3" json:"stale_after_s,omitempty"`                // liveness: online -> stale threshold
	OfflineAfterS    int32                  `protobuf:"varint,6,opt,name=offline_after_s,json=offlineAfterS,proto3" json:"offline_after_s,omitempty"`          // liveness: stale  -> offline threshold
	ClientCertPem    string                 `protobuf:"bytes,7,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`           // optional issued cert when csr_pem was provided
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnrollResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EnrollResponse) GetSampleIntervalMs() int32 {
	if x != nil {
		return x.SampleIntervalMs
	}
	return 0
}

func (x *EnrollResponse) GetStaleAfterS() int32 {
	if x != nil {
		return x.StaleAfterS
	}
	return 0
}

func (x *EnrollResponse) GetOfflineAfterS() int32 {
	if x != nil {
		return x.OfflineAfterS
	}
	return 0
}

func (x *EnrollResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

type AckResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedSeq      uint64                 `protobuf:"varint,1,opt,name=acked_seq,json=ackedSeq,proto3" json:"acked_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResume) Reset() {
	*x = AckResume{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResume) ProtoMessage() {}

func (x *AckResume) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResume.ProtoReflect.Descriptor instead.
func (*AckResume) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *AckResume) GetAckedSeq() uint64 {
	if x != nil {
		return x.AckedSeq
	}
	return 0
}

type CadenceUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SampleIntervalMs int32                  `protobuf:"varint,1,opt,name=sample_interval_ms,json=sampleIntervalMs,proto3" json:"sample_interval_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CadenceUpdate) Reset() {
	*x = CadenceUpdate{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CadenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CadenceUpdate) ProtoMessage() {}

func (x *CadenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CadenceUpdate.ProtoReflect.Descriptor instead.
func (*CadenceUpdate) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{10}
}

func (x *CadenceUpdate) GetSampleIntervalMs() int32 {
	if x != nil {
		return x.SampleIntervalMs
	}
	return 0
}

type KeyframeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyframeRequest) Reset() {
	*x = KeyframeRequest{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyframeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyframeRequest) ProtoMessage() {}

func (x *KeyframeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyframeRequest.ProtoReflect.Descriptor instead.
func (*KeyframeRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{11}
}

func (x *KeyframeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ObservabilityWindow — demand-driven push (v2, ADR 0018). The hub tells the
// daemon whether to push logs / a process table right now, so a configured daemon
// stops pushing them when no dashboard is watching. Absent ⇒ the daemon keeps its
// v1 behaviour (push per config), so old hubs and old daemons are unaffected.
type ObservabilityWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          bool                   `protobuf:"varint,1,opt,name=logs,proto3" json:"logs,omitempty"`
	Processes     bool                   `protobuf:"varint,2,opt,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityWindow) Reset() {
	*x = ObservabilityWindow{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityWindow) ProtoMessage() {}

func (x *ObservabilityWindow) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityWindow.ProtoReflect.Descriptor instead.
func (*ObservabilityWindow) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{12}
}

func (x *ObservabilityWindow) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *ObservabilityWindow) GetProcesses() bool {
	if x != nil {
		return x.Processes
	}
	return false
}

// StreamControl — multiplexed control frames sent from hub to daemon over the
// downstream side of the bidi metric stream (no inbound port on the daemon).
type StreamControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Control:
	//
	//	*StreamControl_Ack
	//	*StreamControl_Cadence
	//	*StreamControl_Keyframe
	//	*StreamControl_Observability
	//	*StreamControl_Run
	Control       isStreamControl_Control `protobuf_oneof:"control"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{13}
}

func (x *StreamControl) GetControl() isStreamControl_Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *StreamControl) GetAck() *AckResume {
	if x != nil {
		if x, ok := x.Control.(*StreamControl_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *StreamControl) GetCadence() *CadenceUpdate {
	if x != nil {
		if x, ok := x.Control.(*StreamControl_Cadence); ok {
			return x.Cadence
		}
	}
	return nil
}

func (x *StreamControl) GetKeyframe() *KeyframeRequest {
	if x != nil {
		if x, ok := x.Control.(*StreamControl_Keyframe); ok {
			return x.Keyframe
		}
	}
	return nil
}

func (x *StreamControl) GetObservability() *ObservabilityWindow {
	if x != nil {
		if x, ok := x.Control.(*StreamControl_Observability); ok {
			return x.Observability
		}
	}
	return nil
}

func (x *StreamControl) GetRun() *ControlRequest {
	if x != nil {
		if x, ok := x.Control.(*StreamControl_Run); ok {
			return x.Run
		}
	}
	return nil
}

type isStreamControl_Control interface {
	isStreamControl_Control()
}

type StreamControl_Ack struct {
	Ack *AckResume `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type StreamControl_Cadence struct {
	Cadence *CadenceUpdate `protobuf:"bytes,2,opt,name=cadence,proto3,oneof"`
}

type StreamControl_Keyframe struct {
	Keyframe *KeyframeRequest `protobuf:"bytes,3,opt,name=keyframe,proto3,oneof"`
}

type StreamControl_Observability struct {
	Observability *ObservabilityWindow `protobuf:"bytes,4,opt,name=observability,proto3,oneof"`
}

type StreamControl_Run struct {
	Run *ControlRequest `protobuf:"bytes,5,opt,name=run,proto3,oneof"` // hub -> daemon: run an allow-listed command (v2)
}

func (*StreamControl_Ack) isStreamControl_Control() {}

func (*StreamControl_Cadence) isStreamControl_Control() {}

func (*StreamControl_Keyframe) isStreamControl_Control() {}

func (*StreamControl_Observability) isStreamControl_Control() {}

func (*StreamControl_Run) isStreamControl_Control() {}

// RelayEnvelope — a child hub relays a snapshot upstream to a parent hub.
// origin_hub_id and path[] provide loop and duplication prevention: a hub drops
// any envelope whose path already contains its own hub id.
type RelayEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginHubId   string                 `protobuf:"bytes,1,opt,name=origin_hub_id,json=originHubId,proto3" json:"origin_hub_id,omitempty"` // first hub that ingested the snapshot
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`                                    // ordered hub ids traversed so far
	Snapshot      *Snapshot              `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEnvelope) Reset() {
	*x = RelayEnvelope{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEnvelope) ProtoMessage() {}

func (x *RelayEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEnvelope.ProtoReflect.Descriptor instead.
func (*RelayEnvelope) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{14}
}

func (x *RelayEnvelope) GetOriginHubId() string {
	if x != nil {
		return x.OriginHubId
	}
	return ""
}

func (x *RelayEnvelope) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RelayEnvelope) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RelayControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedSeq      uint64                 `protobuf:"varint,1,opt,name=acked_seq,json=ackedSeq,proto3" json:"acked_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayControl) Reset() {
	*x = RelayControl{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayControl) ProtoMessage() {}

func (x *RelayControl) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayControl.ProtoReflect.Descriptor instead.
func (*RelayControl) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{15}
}

func (x *RelayControl) GetAckedSeq() uint64 {
	if x != nil {
		return x.AckedSeq
	}
	return 0
}

// SubscribeRequest — a dashboard or peer hub subscribes to a hub's MetricBus.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	HostIds       []string               `protobuf:"bytes,2,rep,name=host_ids,json=hostIds,proto3" json:"host_ids,omitempty"`           // empty = all hosts
	DeltasOnly    bool                   `protobuf:"varint,3,opt,name=deltas_only,json=deltasOnly,proto3" json:"deltas_only,omitempty"` // true = skip keyframes after initial sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetHostIds() []string {
	if x != nil {
		return x.HostIds
	}
	return nil
}

func (x *SubscribeRequest) GetDeltasOnly() bool {
	if x != nil {
		return x.DeltasOnly
	}
	return false
}

// CommandAck — synchronous acknowledgement that the hub accepted and routed an
// on-demand command. The actual result arrives later on the host's snapshot.
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // false when the host is unknown or not connected
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{17}
}

func (x *CommandAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ControlRequest — dashboard -> daemon. allowlisted_cmd is a LOGICAL command
// key validated against a static allow-list; it is never a shell string. args
// are typed/validated tokens, never concatenated into a shell. Commands run as
// the unprivileged daemon user. No sudo. No arbitrary execution.
type ControlRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AllowlistedCmd string                 `protobuf:"bytes,3,opt,name=allowlisted_cmd,json=allowlistedCmd,proto3" json:"allowlisted_cmd,omitempty"` // logical key, e.g. "process.list" | "disk.df"
	Args           []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                                           // validated argument tokens
	Actor          string                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`                                         // authenticated dashboard principal (for audit)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{18}
}

func (x *ControlRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ControlRequest) GetAllowlistedCmd() string {
	if x != nil {
		return x.AllowlistedCmd
	}
	return ""
}

func (x *ControlRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ControlRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

// ControlResponse — bounded result. status=INSUFFICIENT_PERMISSION when the
// allow-list or arg validation rejects the request. truncated=true when stdout
// hit the output cap.
type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Status        MetricStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=monitoring.v1.MetricStatus" json:"status,omitempty"` // OK | INSUFFICIENT_PERMISSION | ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{19}
}

func (x *ControlResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ControlResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ControlResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ControlResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ControlResponse) GetStatus() MetricStatus {
	if x != nil {
		return x.Status
	}
	return MetricStatus_METRIC_STATUS_UNSPECIFIED
}

// LogTailRequest — opt-in per-source tail. sources are explicit opt-in keys
// (a journald unit alias or a registered file alias), never arbitrary paths.
type LogTailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Sources        []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`                                          // opt-in source keys
	MaxLinesPerSec int32                  `protobuf:"varint,3,opt,name=max_lines_per_sec,json=maxLinesPerSec,proto3" json:"max_lines_per_sec,omitempty"` // client-requested cap; hub/daemon may lower it
	Filter         string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`                                            // server-side substring / severity filter
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogTailRequest) Reset() {
	*x = LogTailRequest{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTailRequest) ProtoMessage() {}

func (x *LogTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTailRequest.ProtoReflect.Descriptor instead.
func (*LogTailRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{20}
}

func (x *LogTailRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogTailRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *LogTailRequest) GetMaxLinesPerSec() int32 {
	if x != nil {
		return x.MaxLinesPerSec
	}
	return 0
}

func (x *LogTailRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// LogLine — one tailed line. rate_limited=true means lines were dropped before
// this one to honour the rate cap.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	TsUnixMillis  int64                  `protobuf:"varint,3,opt,name=ts_unix_millis,json=tsUnixMillis,proto3" json:"ts_unix_millis,omitempty"`
	Line          string                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"` // optional parsed severity
	RateLimited   bool                   `protobuf:"varint,6,opt,name=rate_limited,json=rateLimited,proto3" json:"rate_limited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_v1_monitoring_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{21}
}

func (x *LogLine) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogLine) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogLine) GetTsUnixMillis() int64 {
	if x != nil {
		return x.TsUnixMillis
	}
	return 0
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetRateLimited() bool {
	if x != nil {
		return x.RateLimited
	}
	return false
}

var File_monitoring_v1_monitoring_proto protoreflect.FileDescriptor

const file_monitoring_v1_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x1emonitoring/v1/monitoring.proto\x12\rmonitoring.v1\"\x94\x01\n" +
	"\x04Host\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x124\n" +
	"\acontext\x18\x04 \x01(\v2\x1a.monitoring.v1.HostContextR\acontext\"\xe5\x02\n" +
	"\vHostContext\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12'\n" +
	"\x10boot_time_unix_s\x18\a \x01(\x03R\rbootTimeUnixS\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12>\n" +
	"\x06labels\x18\t \x03(\v2&.monitoring.v1.HostContext.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\aPerCore\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x01B\x02\x10\x01R\x06values\"3\n" +
	"\aCounter\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\"\x91\x02\n" +
	"\fMetricSample\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.monitoring.v1.MetricStatusR\x06status\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x05gauge\x18\x05 \x01(\x01H\x00R\x05gauge\x123\n" +
	"\bper_core\x18\x06 \x01(\v2\x16.monitoring.v1.PerCoreH\x00R\aperCore\x122\n" +
	"\acounter\x18\a \x01(\v2\x16.monitoring.v1.CounterH\x00R\acounterB\a\n" +
	"\x05value\"~\n" +
	"\n" +
	"ProcessRow\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x02R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x04 \x01(\x02R\x06memPct\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"\xe6\x04\n" +
	"\bSnapshot\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12$\n" +
	"\x0ets_unix_millis\x18\x02 \x01(\x03R\ftsUnixMillis\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\bR\x05delta\x12\x1a\n" +
	"\bkeyframe\x18\x05 \x01(\bR\bkeyframe\x125\n" +
	"\asamples\x18\x06 \x03(\v2\x1b.monitoring.v1.MetricSampleR\asamples\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.monitoring.v1.Snapshot.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06alerts\x18\b \x03(\tR\x06alerts\x127\n" +
	"\tprocesses\x18\t \x03(\v2\x19.monitoring.v1.ProcessRowR\tprocesses\x127\n" +
	"\x18processes_at_unix_millis\x18\n" +
	" \x01(\x03R\x15processesAtUnixMillis\x123\n" +
	"\tlog_lines\x18\v \x03(\v2\x16.monitoring.v1.LogLineR\blogLines\x12E\n" +
	"\x0ecommand_result\x18\f \x01(\v2\x1e.monitoring.v1.ControlResponseR\rcommandResult\x12\"\n" +
	"\fdisconnected\x18\r \x01(\bR\fdisconnected\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12'\n" +
	"\x04host\x18\x02 \x01(\v2\x13.monitoring.v1.HostR\x04host\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\"\xff\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12,\n" +
	"\x12sample_interval_ms\x18\x04 \x01(\x05R\x10sampleIntervalMs\x12\"\n" +
	"\rstale_after_s\x18\x05 \x01(\x05R\vstaleAfterS\x12&\n" +
	"\x0foffline_after_s\x18\x06 \x01(\x05R\rofflineAfterS\x12&\n" +
	"\x0fclient_cert_pem\x18\a \x01(\tR\rclientCertPem\"(\n" +
	"\tAckResume\x12\x1b\n" +
	"\tacked_seq\x18\x01 \x01(\x04R\backedSeq\"=\n" +
	"\rCadenceUpdate\x12,\n" +
	"\x12sample_interval_ms\x18\x01 \x01(\x05R\x10sampleIntervalMs\")\n" +
	"\x0fKeyframeRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"G\n" +
	"\x13ObservabilityWindow\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\bR\x04logs\x12\x1c\n" +
	"\tprocesses\x18\x02 \x01(\bR\tprocesses\"\xbf\x02\n" +
	"\rStreamControl\x12,\n" +
	"\x03ack\x18\x01 \x01(\v2\x18.monitoring.v1.AckResumeH\x00R\x03ack\x128\n" +
	"\acadence\x18\x02 \x01(\v2\x1c.monitoring.v1.CadenceUpdateH\x00R\acadence\x12<\n" +
	"\bkeyframe\x18\x03 \x01(\v2\x1e.monitoring.v1.KeyframeRequestH\x00R\bkeyframe\x12J\n" +
	"\robservability\x18\x04 \x01(\v2\".monitoring.v1.ObservabilityWindowH\x00R\robservability\x121\n" +
	"\x03run\x18\x05 \x01(\v2\x1d.monitoring.v1.ControlRequestH\x00R\x03runB\t\n" +
	"\acontrol\"|\n" +
	"\rRelayEnvelope\x12\"\n" +
	"\rorigin_hub_id\x18\x01 \x01(\tR\voriginHubId\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\x123\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x17.monitoring.v1.SnapshotR\bsnapshot\"+\n" +
	"\fRelayControl\x12\x1b\n" +
	"\tacked_seq\x18\x01 \x01(\x04R\backedSeq\"s\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x19\n" +
	"\bhost_ids\x18\x02 \x03(\tR\ahostIds\x12\x1f\n" +
	"\vdeltas_only\x18\x03 \x01(\bR\n" +
	"deltasOnly\"]\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x0eControlRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12'\n" +
	"\x0fallowlisted_cmd\x18\x03 \x01(\tR\x0eallowlistedCmd\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\"\xd0\x01\n" +
	"\x0fControlResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.monitoring.v1.MetricStatusR\x06status\"\x86\x01\n" +
	"\x0eLogTailRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12)\n" +
	"\x11max_lines_per_sec\x18\x03 \x01(\x05R\x0emaxLinesPerSec\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\xad\x01\n" +
	"\aLogLine\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\x0ets_unix_millis\x18\x03 \x01(\x03R\ftsUnixMillis\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12!\n" +
	"\frate_limited\x18\x06 \x01(\bR\vrateLimited*\xa6\x01\n" +
	"\fMetricStatus\x12\x1d\n" +
	"\x19METRIC_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10METRIC_STATUS_OK\x10\x01\x12\x1d\n" +
	"\x19METRIC_STATUS_UNAVAILABLE\x10\x02\x12)\n" +
	"%METRIC_STATUS_INSUFFICIENT_PERMISSION\x10\x03\x12\x17\n" +
	"\x13METRIC_STATUS_ERROR\x10\x042\xec\x01\n" +
	"\x11FederationService\x12F\n" +
	"\x05Relay\x12\x1c.monitoring.v1.RelayEnvelope\x1a\x1b.monitoring.v1.RelayControl(\x010\x01\x12G\n" +
	"\tSubscribe\x12\x1f.monitoring.v1.SubscribeRequest\x1a\x17.monitoring.v1.Snapshot0\x01\x12F\n" +
	"\n" +
	"RunCommand\x12\x1d.monitoring.v1.ControlRequest\x1a\x19.monitoring.v1.CommandAck2c\n" +
	"\x13ControlPlaneService\x12L\n" +
	"\aExecute\x12\x1d.monitoring.v1.ControlRequest\x1a\x1e.monitoring.v1.ControlResponse(\x010\x012S\n" +
	"\x10LogStreamService\x12?\n" +
	"\x04Tail\x12\x1d.monitoring.v1.LogTailRequest\x1a\x16.monitoring.v1.LogLine0\x012Z\n" +
	"\x11EnrollmentService\x12E\n" +
	"\x06Enroll\x12\x1c.monitoring.v1.EnrollRequest\x1a\x1d.monitoring.v1.EnrollResponse2Z\n" +
	"\x13MetricStreamService\x12C\n" +
	"\x06Stream\x12\x17.monitoring.v1.Snapshot\x1a\x1c.monitoring.v1.StreamControl(\x010\x01B2Z0heimdall/common/proto/monitoring/v1;monitoringv1b\x06proto3"

var (
	file_monitoring_v1_monitoring_proto_rawDescOnce sync.Once
	file_monitoring_v1_monitoring_proto_rawDescData []byte
)

func file_monitoring_v1_monitoring_proto_rawDescGZIP() []byte {
	file_monitoring_v1_monitoring_proto_rawDescOnce.Do(func() {
		file_monitoring_v1_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitoring_v1_monitoring_proto_rawDesc), len(file_monitoring_v1_monitoring_proto_rawDesc)))
	})
	return file_monitoring_v1_monitoring_proto_rawDescData
}

var file_monitoring_v1_monitoring_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monitoring_v1_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_monitoring_v1_monitoring_proto_goTypes = []any{
	(MetricStatus)(0),           // 0: monitoring.v1.MetricStatus
	(*Host)(nil),                // 1: monitoring.v1.Host
	(*HostContext)(nil),         // 2: monitoring.v1.HostContext
	(*PerCore)(nil),             // 3: monitoring.v1.PerCore
	(*Counter)(nil),             // 4: monitoring.v1.Counter
	(*MetricSample)(nil),        // 5: monitoring.v1.MetricSample
	(*ProcessRow)(nil),          // 6: monitoring.v1.ProcessRow
	(*Snapshot)(nil),            // 7: monitoring.v1.Snapshot
	(*EnrollRequest)(nil),       // 8: monitoring.v1.EnrollRequest
	(*EnrollResponse)(nil),      // 9: monitoring.v1.EnrollResponse
	(*AckResume)(nil),           // 10: monitoring.v1.AckResume
	(*CadenceUpdate)(nil),       // 11: monitoring.v1.CadenceUpdate
	(*KeyframeRequest)(nil),     // 12: monitoring.v1.KeyframeRequest
	(*ObservabilityWindow)(nil), // 13: monitoring.v1.ObservabilityWindow
	(*StreamControl)(nil),       // 14: monitoring.v1.StreamControl
	(*RelayEnvelope)(nil),       // 15: monitoring.v1.RelayEnvelope
	(*RelayControl)(nil),        // 16: monitoring.v1.RelayControl
	(*SubscribeRequest)(nil),    // 17: monitoring.v1.SubscribeRequest
	(*CommandAck)(nil),          // 18: monitoring.v1.CommandAck
	(*ControlRequest)(nil),      // 19: monitoring.v1.ControlRequest
	(*ControlResponse)(nil),     // 20: monitoring.v1.ControlResponse
	(*LogTailRequest)(nil),      // 21: monitoring.v1.LogTailRequest
	(*LogLine)(nil),             // 22: monitoring.v1.LogLine
	nil,                         // 23: monitoring.v1.HostContext.LabelsEntry
	nil,                         // 24: monitoring.v1.Snapshot.LabelsEntry
}
var file_monitoring_v1_monitoring_proto_depIdxs = []int32{
	2,  // 0: monitoring.v1.Host.context:type_name -> monitoring.v1.HostContext
	23, // 1: monitoring.v1.HostContext.labels:type_name -> monitoring.v1.HostContext.LabelsEntry
	0,  // 2: monitoring.v1.MetricSample.status:type_name -> monitoring.v1.MetricStatus
	3,  // 3: monitoring.v1.MetricSample.per_core:type_name -> monitoring.v1.PerCore
	4,  // 4: monitoring.v1.MetricSample.counter:type_name -> monitoring.v1.Counter
	5,  // 5: monitoring.v1.Snapshot.samples:type_name -> monitoring.v1.MetricSample
	24, // 6: monitoring.v1.Snapshot.labels:type_name -> monitoring.v1.Snapshot.LabelsEntry
	6,  // 7: monitoring.v1.Snapshot.processes:type_name -> monitoring.v1.ProcessRow
	22, // 8: monitoring.v1.Snapshot.log_lines:type_name -> monitoring.v1.LogLine
	20, // 9: monitoring.v1.Snapshot.command_result:type_name -> monitoring.v1.ControlResponse
	1,  // 10: monitoring.v1.EnrollRequest.host:type_name -> monitoring.v1.Host
	10, // 11: monitoring.v1.StreamControl.ack:type_name -> monitoring.v1.AckResume
	11, // 12: monitoring.v1.StreamControl.cadence:type_name -> monitoring.v1.CadenceUpdate
	12, // 13: monitoring.v1.StreamControl.keyframe:type_name -> monitoring.v1.KeyframeRequest
	13, // 14: monitoring.v1.StreamControl.observability:type_name -> monitoring.v1.ObservabilityWindow
	19, // 15: monitoring.v1.StreamControl.run:type_name -> monitoring.v1.ControlRequest
	7,  // 16: monitoring.v1.RelayEnvelope.snapshot:type_name -> monitoring.v1.Snapshot
	0,  // 17: monitoring.v1.ControlResponse.status:type_name -> monitoring.v1.MetricStatus
	15, // 18: monitoring.v1.FederationService.Relay:input_type -> monitoring.v1.RelayEnvelope
	17, // 19: monitoring.v1.FederationService.Subscribe:input_type -> monitoring.v1.SubscribeRequest
	19, // 20: monitoring.v1.FederationService.RunCommand:input_type -> monitoring.v1.ControlRequest
	19, // 21: monitoring.v1.ControlPlaneService.Execute:input_type -> monitoring.v1.ControlRequest
	21, // 22: monitoring.v1.LogStreamService.Tail:input_type -> monitoring.v1.LogTailRequest
	8,  // 23: monitoring.v1.EnrollmentService.Enroll:input_type -> monitoring.v1.EnrollRequest
	7,  // 24: monitoring.v1.MetricStreamService.Stream:input_type -> monitoring.v1.Snapshot
	16, // 25: monitoring.v1.FederationService.Relay:output_type -> monitoring.v1.RelayControl
	7,  // 26: monitoring.v1.FederationService.Subscribe:output_type -> monitoring.v1.Snapshot
	18, // 27: monitoring.v1.FederationService.RunCommand:output_type -> monitoring.v1.CommandAck
	20, // 28: monitoring.v1.ControlPlaneService.Execute:output_type -> monitoring.v1.ControlResponse
	22, // 29: monitoring.v1.LogStreamService.Tail:output_type -> monitoring.v1.LogLine
	9,  // 30: monitoring.v1.EnrollmentService.Enroll:output_type -> monitoring.v1.EnrollResponse
	14, // 31: monitoring.v1.MetricStreamService.Stream:output_type -> monitoring.v1.StreamControl
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_monitoring_v1_monitoring_proto_init() }
func file_monitoring_v1_monitoring_proto_init() {
	if File_monitoring_v1_monitoring_proto != nil {
		return
	}
	file_monitoring_v1_monitoring_proto_msgTypes[4].OneofWrappers = []any{
		(*MetricSample_Gauge)(nil),
		(*MetricSample_PerCore)(nil),
		(*MetricSample_Counter)(nil),
	}
	file_monitoring_v1_monitoring_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamControl_Ack)(nil),
		(*StreamControl_Cadence)(nil),
		(*StreamControl_Keyframe)(nil),
		(*StreamControl_Observability)(nil),
		(*StreamControl_Run)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitoring_v1_monitoring_proto_rawDesc), len(file_monitoring_v1_monitoring_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_monitoring_v1_monitoring_proto_goTypes,
		DependencyIndexes: file_monitoring_v1_monitoring_proto_depIdxs,
		EnumInfos:         file_monitoring_v1_monitoring_proto_enumTypes,
		MessageInfos:      file_monitoring_v1_monitoring_proto_msgTypes,
	}.Build()
	File_monitoring_v1_monitoring_proto = out.File
	file_monitoring_v1_monitoring_proto_goTypes = nil
	file_monitoring_v1_monitoring_proto_depIdxs = nil
}
