// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Kinn Coelho Juliao <kinncj@gmail.com>
//
// Heimdall monitoring contract — version 1.
//
// Single source of truth for the wire protocol shared by ALL binaries
// (heimdall-daemon, heimdall-helper, heimdall-hub, heimdall-dashboard).
// Every binary imports the generated types from this file; none defines a
// private copy. Versioning policy: see README.md in this directory.
//
// Design constraints reflected here:
//   - Low bandwidth: compact scalar timestamps (int64 unix-millis, no
//     well-known-type sub-message per sample), packed per-core arrays,
//     delta/keyframe snapshots, monotonic per-host sequence for resume.
//   - Failure isolation: every MetricSample carries its own MetricStatus, so
//     one failing metric is reported without dropping the host or siblings.
//   - Clean boundary: this file is a transport CONTRACT only. It contains no
//     business logic and no Go code. Domain types map to these messages at the
//     transport layer, never the reverse.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: monitoring/v1/monitoring.proto

package monitoringv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationService_Relay_FullMethodName     = "/monitoring.v1.FederationService/Relay"
	FederationService_Subscribe_FullMethodName = "/monitoring.v1.FederationService/Subscribe"
)

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FederationService — cross-hub relay and fan-out. Cross-hub mTLS + token.
type FederationServiceClient interface {
	// Child -> parent: relay merged snapshots upstream as a bus subscriber.
	Relay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayEnvelope, RelayControl], error)
	// Subscribe to a hub's bus (used by dashboards and peer/parent hubs).
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) Relay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayEnvelope, RelayControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[0], FederationService_Relay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RelayEnvelope, RelayControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_RelayClient = grpc.BidiStreamingClient[RelayEnvelope, RelayControl]

func (c *federationServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[1], FederationService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Snapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_SubscribeClient = grpc.ServerStreamingClient[Snapshot]

// FederationServiceServer is the server API for FederationService service.
// All implementations must embed UnimplementedFederationServiceServer
// for forward compatibility.
//
// FederationService — cross-hub relay and fan-out. Cross-hub mTLS + token.
type FederationServiceServer interface {
	// Child -> parent: relay merged snapshots upstream as a bus subscriber.
	Relay(grpc.BidiStreamingServer[RelayEnvelope, RelayControl]) error
	// Subscribe to a hub's bus (used by dashboards and peer/parent hubs).
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Snapshot]) error
	mustEmbedUnimplementedFederationServiceServer()
}

// UnimplementedFederationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServiceServer struct{}

func (UnimplementedFederationServiceServer) Relay(grpc.BidiStreamingServer[RelayEnvelope, RelayControl]) error {
	return status.Error(codes.Unimplemented, "method Relay not implemented")
}
func (UnimplementedFederationServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Snapshot]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedFederationServiceServer) mustEmbedUnimplementedFederationServiceServer() {}
func (UnimplementedFederationServiceServer) testEmbeddedByValue()                           {}

// UnsafeFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServiceServer will
// result in compilation errors.
type UnsafeFederationServiceServer interface {
	mustEmbedUnimplementedFederationServiceServer()
}

func RegisterFederationServiceServer(s grpc.ServiceRegistrar, srv FederationServiceServer) {
	// If the following call panics, it indicates UnimplementedFederationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationService_ServiceDesc, srv)
}

func _FederationService_Relay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FederationServiceServer).Relay(&grpc.GenericServerStream[RelayEnvelope, RelayControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_RelayServer = grpc.BidiStreamingServer[RelayEnvelope, RelayControl]

func _FederationService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Snapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_SubscribeServer = grpc.ServerStreamingServer[Snapshot]

// FederationService_ServiceDesc is the grpc.ServiceDesc for FederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Relay",
			Handler:       _FederationService_Relay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _FederationService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitoring/v1/monitoring.proto",
}

const (
	ControlPlaneService_Execute_FullMethodName = "/monitoring.v1.ControlPlaneService/Execute"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlaneService — single authenticated, audit-logged control channel.
type ControlPlaneServiceClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlRequest, ControlResponse], error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlRequest, ControlResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlRequest, ControlResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ExecuteClient = grpc.BidiStreamingClient[ControlRequest, ControlResponse]

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// ControlPlaneService — single authenticated, audit-logged control channel.
type ControlPlaneServiceServer interface {
	Execute(grpc.BidiStreamingServer[ControlRequest, ControlResponse]) error
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) Execute(grpc.BidiStreamingServer[ControlRequest, ControlResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServiceServer).Execute(&grpc.GenericServerStream[ControlRequest, ControlResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ExecuteServer = grpc.BidiStreamingServer[ControlRequest, ControlResponse]

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ControlPlaneService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitoring/v1/monitoring.proto",
}

const (
	LogStreamService_Tail_FullMethodName = "/monitoring.v1.LogStreamService/Tail"
)

// LogStreamServiceClient is the client API for LogStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogStreamService — opt-in log tailing on its own stream so log volume can
// never back-pressure or starve the metric stream.
type LogStreamServiceClient interface {
	Tail(ctx context.Context, in *LogTailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type logStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamServiceClient(cc grpc.ClientConnInterface) LogStreamServiceClient {
	return &logStreamServiceClient{cc}
}

func (c *logStreamServiceClient) Tail(ctx context.Context, in *LogTailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStreamService_ServiceDesc.Streams[0], LogStreamService_Tail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogTailRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamService_TailClient = grpc.ServerStreamingClient[LogLine]

// LogStreamServiceServer is the server API for LogStreamService service.
// All implementations must embed UnimplementedLogStreamServiceServer
// for forward compatibility.
//
// LogStreamService — opt-in log tailing on its own stream so log volume can
// never back-pressure or starve the metric stream.
type LogStreamServiceServer interface {
	Tail(*LogTailRequest, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedLogStreamServiceServer()
}

// UnimplementedLogStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStreamServiceServer struct{}

func (UnimplementedLogStreamServiceServer) Tail(*LogTailRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method Tail not implemented")
}
func (UnimplementedLogStreamServiceServer) mustEmbedUnimplementedLogStreamServiceServer() {}
func (UnimplementedLogStreamServiceServer) testEmbeddedByValue()                          {}

// UnsafeLogStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStreamServiceServer will
// result in compilation errors.
type UnsafeLogStreamServiceServer interface {
	mustEmbedUnimplementedLogStreamServiceServer()
}

func RegisterLogStreamServiceServer(s grpc.ServiceRegistrar, srv LogStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedLogStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStreamService_ServiceDesc, srv)
}

func _LogStreamService_Tail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogTailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogStreamServiceServer).Tail(m, &grpc.GenericServerStream[LogTailRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamService_TailServer = grpc.ServerStreamingServer[LogLine]

// LogStreamService_ServiceDesc is the grpc.ServiceDesc for LogStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.LogStreamService",
	HandlerType: (*LogStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tail",
			Handler:       _LogStreamService_Tail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitoring/v1/monitoring.proto",
}

const (
	EnrollmentService_Enroll_FullMethodName = "/monitoring.v1.EnrollmentService/Enroll"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnrollmentService — bootstrap a daemon's identity and obtain stream policy.
type EnrollmentServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
//
// EnrollmentService — bootstrap a daemon's identity and obtain stream policy.
type EnrollmentServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _EnrollmentService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitoring/v1/monitoring.proto",
}

const (
	MetricStreamService_Stream_FullMethodName = "/monitoring.v1.MetricStreamService/Stream"
)

// MetricStreamServiceClient is the client API for MetricStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricStreamService — primary bidirectional metric channel.
// Upstream: daemon streams Snapshots. Downstream: hub streams StreamControl
// (resume acks, cadence retune, keyframe requests).
type MetricStreamServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Snapshot, StreamControl], error)
}

type metricStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricStreamServiceClient(cc grpc.ClientConnInterface) MetricStreamServiceClient {
	return &metricStreamServiceClient{cc}
}

func (c *metricStreamServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Snapshot, StreamControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricStreamService_ServiceDesc.Streams[0], MetricStreamService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Snapshot, StreamControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricStreamService_StreamClient = grpc.BidiStreamingClient[Snapshot, StreamControl]

// MetricStreamServiceServer is the server API for MetricStreamService service.
// All implementations must embed UnimplementedMetricStreamServiceServer
// for forward compatibility.
//
// MetricStreamService — primary bidirectional metric channel.
// Upstream: daemon streams Snapshots. Downstream: hub streams StreamControl
// (resume acks, cadence retune, keyframe requests).
type MetricStreamServiceServer interface {
	Stream(grpc.BidiStreamingServer[Snapshot, StreamControl]) error
	mustEmbedUnimplementedMetricStreamServiceServer()
}

// UnimplementedMetricStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricStreamServiceServer struct{}

func (UnimplementedMetricStreamServiceServer) Stream(grpc.BidiStreamingServer[Snapshot, StreamControl]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMetricStreamServiceServer) mustEmbedUnimplementedMetricStreamServiceServer() {}
func (UnimplementedMetricStreamServiceServer) testEmbeddedByValue()                             {}

// UnsafeMetricStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricStreamServiceServer will
// result in compilation errors.
type UnsafeMetricStreamServiceServer interface {
	mustEmbedUnimplementedMetricStreamServiceServer()
}

func RegisterMetricStreamServiceServer(s grpc.ServiceRegistrar, srv MetricStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricStreamService_ServiceDesc, srv)
}

func _MetricStreamService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricStreamServiceServer).Stream(&grpc.GenericServerStream[Snapshot, StreamControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricStreamService_StreamServer = grpc.BidiStreamingServer[Snapshot, StreamControl]

// MetricStreamService_ServiceDesc is the grpc.ServiceDesc for MetricStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.MetricStreamService",
	HandlerType: (*MetricStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _MetricStreamService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitoring/v1/monitoring.proto",
}
